/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityFeedEntry {
  'activityType' : string,
  'userId' : Principal,
  'xpGained' : bigint,
  'message' : string,
  'timestamp' : bigint,
}
export interface BodyMetric {
  'bmi' : number,
  'weight' : number,
  'bodyFat' : number,
  'hips' : number,
  'chest' : number,
  'timestamp' : bigint,
  'waist' : number,
  'biceps' : number,
}
export interface Challenge {
  'id' : bigint,
  'durationDays' : bigint,
  'badgeIcon' : string,
  'name' : string,
  'description' : string,
  'rewardXp' : bigint,
  'targetCount' : bigint,
}
export interface Exercise {
  'id' : bigint,
  'equipment' : string,
  'musclesWorked' : Array<string>,
  'difficulty' : ExerciseDifficulty,
  'name' : string,
  'tier' : string,
  'instructions' : Array<string>,
  'category' : ExerciseCategory,
  'commonMistakes' : Array<string>,
  'setsReps' : string,
}
export type ExerciseCategory = { 'shoulders' : null } |
  { 'arms' : null } |
  { 'back' : null } |
  { 'core' : null } |
  { 'chest' : null } |
  { 'legs' : null } |
  { 'fullBody' : null };
export type ExerciseDifficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'receiverId' : Principal,
  'timestamp' : bigint,
  'senderId' : Principal,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface NotificationPreferences {
  'levelups' : boolean,
  'friends' : boolean,
  'challenges' : boolean,
  'streaks' : boolean,
}
export type NotificationType = { 'streak' : null } |
  { 'levelup' : null } |
  { 'challenge' : null } |
  { 'friendAchievement' : null };
export interface SleepData {
  'hours' : number,
  'bedtime' : string,
  'quality' : bigint,
  'wakeTime' : string,
}
export interface UserChallenge {
  'joinedAt' : bigint,
  'completed' : boolean,
  'challengeId' : bigint,
  'currentCount' : bigint,
}
export interface UserProfile {
  'xp' : bigint,
  'streak' : bigint,
  'username' : string,
  'fitnessGoal' : string,
  'activeTheme' : string,
  'level' : bigint,
  'lastWorkoutDate' : bigint,
  'isBanned' : boolean,
  'isAdmin' : boolean,
  'profilePic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellnessLog {
  'userId' : Principal,
  'date' : bigint,
  'sleepData' : SleepData,
  'hydration' : bigint,
}
export interface WorkoutLog {
  'completedAt' : bigint,
  'exerciseId' : bigint,
  'xpAwarded' : bigint,
  'notes' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBodyMetric' : ActorMethod<[BodyMetric], undefined>,
  'addExercise' : ActorMethod<[Exercise], bigint>,
  'addNotification' : ActorMethod<
    [Principal, NotificationType, string],
    bigint
  >,
  'addWellnessLog' : ActorMethod<[WellnessLog], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createChallenge' : ActorMethod<[Challenge], bigint>,
  'deleteChallenge' : ActorMethod<[bigint], undefined>,
  'deleteExercise' : ActorMethod<[bigint], undefined>,
  'editChallenge' : ActorMethod<[bigint, Challenge], undefined>,
  'editExercise' : ActorMethod<[bigint, Exercise], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getActivityFeed' : ActorMethod<[], Array<ActivityFeedEntry>>,
  'getAdminUserList' : ActorMethod<[], Array<UserProfile>>,
  'getAllChallenges' : ActorMethod<[], Array<Challenge>>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerAchievements' : ActorMethod<[], Array<bigint>>,
  'getCallerBodyMetrics' : ActorMethod<[], Array<BodyMetric>>,
  'getCallerChallenges' : ActorMethod<[], Array<UserChallenge>>,
  'getCallerNotificationPreferences' : ActorMethod<[], NotificationPreferences>,
  'getCallerNotifications' : ActorMethod<[], Array<Notification>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWellnessLogs' : ActorMethod<[], Array<WellnessLog>>,
  'getCallerWorkoutLogs' : ActorMethod<[], Array<WorkoutLog>>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getExerciseById' : ActorMethod<[bigint], [] | [Exercise]>,
  'getExercisesByCategory' : ActorMethod<[ExerciseCategory], Array<Exercise>>,
  'getGlobalLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getRecommendedExercises' : ActorMethod<[], Array<Exercise>>,
  'getReportedContent' : ActorMethod<[], Array<[bigint, string]>>,
  'getStreakLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'isBanned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinChallenge' : ActorMethod<[bigint], undefined>,
  'logWorkout' : ActorMethod<[bigint, string], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'moderateContent' : ActorMethod<[bigint, string], undefined>,
  'reportUser' : ActorMethod<[Principal, string], undefined>,
  'saveCallerNotificationPreferences' : ActorMethod<
    [NotificationPreferences],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'updateActiveTheme' : ActorMethod<[string], undefined>,
  'updateCallerProfile' : ActorMethod<
    [string, string, bigint, bigint, bigint, [] | [ExternalBlob]],
    undefined
  >,
  'updateChallengeProgress' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];