/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BodyMetric = IDL.Record({
  'bmi' : IDL.Float64,
  'weight' : IDL.Float64,
  'bodyFat' : IDL.Float64,
  'hips' : IDL.Float64,
  'chest' : IDL.Float64,
  'timestamp' : IDL.Int,
  'waist' : IDL.Float64,
  'biceps' : IDL.Float64,
});
export const ExerciseDifficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const ExerciseCategory = IDL.Variant({
  'shoulders' : IDL.Null,
  'arms' : IDL.Null,
  'back' : IDL.Null,
  'core' : IDL.Null,
  'chest' : IDL.Null,
  'legs' : IDL.Null,
  'fullBody' : IDL.Null,
});
export const Exercise = IDL.Record({
  'id' : IDL.Nat,
  'equipment' : IDL.Text,
  'musclesWorked' : IDL.Vec(IDL.Text),
  'difficulty' : ExerciseDifficulty,
  'name' : IDL.Text,
  'tier' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'category' : ExerciseCategory,
  'commonMistakes' : IDL.Vec(IDL.Text),
  'setsReps' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'streak' : IDL.Null,
  'levelup' : IDL.Null,
  'challenge' : IDL.Null,
  'friendAchievement' : IDL.Null,
});
export const SleepData = IDL.Record({
  'hours' : IDL.Float64,
  'bedtime' : IDL.Text,
  'quality' : IDL.Nat,
  'wakeTime' : IDL.Text,
});
export const WellnessLog = IDL.Record({
  'userId' : IDL.Principal,
  'date' : IDL.Int,
  'sleepData' : SleepData,
  'hydration' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : IDL.Nat,
  'durationDays' : IDL.Nat,
  'badgeIcon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'rewardXp' : IDL.Nat,
  'targetCount' : IDL.Nat,
});
export const ActivityFeedEntry = IDL.Record({
  'activityType' : IDL.Text,
  'userId' : IDL.Principal,
  'xpGained' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'streak' : IDL.Nat,
  'username' : IDL.Text,
  'fitnessGoal' : IDL.Text,
  'activeTheme' : IDL.Text,
  'level' : IDL.Nat,
  'lastWorkoutDate' : IDL.Int,
  'isBanned' : IDL.Bool,
  'isAdmin' : IDL.Bool,
  'profilePic' : IDL.Opt(ExternalBlob),
});
export const UserChallenge = IDL.Record({
  'joinedAt' : IDL.Int,
  'completed' : IDL.Bool,
  'challengeId' : IDL.Nat,
  'currentCount' : IDL.Nat,
});
export const NotificationPreferences = IDL.Record({
  'levelups' : IDL.Bool,
  'friends' : IDL.Bool,
  'challenges' : IDL.Bool,
  'streaks' : IDL.Bool,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'notificationType' : NotificationType,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const WorkoutLog = IDL.Record({
  'completedAt' : IDL.Int,
  'exerciseId' : IDL.Nat,
  'xpAwarded' : IDL.Nat,
  'notes' : IDL.Text,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'receiverId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'senderId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBodyMetric' : IDL.Func([BodyMetric], [], []),
  'addExercise' : IDL.Func([Exercise], [IDL.Nat], []),
  'addNotification' : IDL.Func(
      [IDL.Principal, NotificationType, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addWellnessLog' : IDL.Func([WellnessLog], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createChallenge' : IDL.Func([Challenge], [IDL.Nat], []),
  'deleteChallenge' : IDL.Func([IDL.Nat], [], []),
  'deleteExercise' : IDL.Func([IDL.Nat], [], []),
  'editChallenge' : IDL.Func([IDL.Nat, Challenge], [], []),
  'editExercise' : IDL.Func([IDL.Nat, Exercise], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getActivityFeed' : IDL.Func([], [IDL.Vec(ActivityFeedEntry)], ['query']),
  'getAdminUserList' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerAchievements' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getCallerBodyMetrics' : IDL.Func([], [IDL.Vec(BodyMetric)], ['query']),
  'getCallerChallenges' : IDL.Func([], [IDL.Vec(UserChallenge)], ['query']),
  'getCallerNotificationPreferences' : IDL.Func(
      [],
      [NotificationPreferences],
      ['query'],
    ),
  'getCallerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWellnessLogs' : IDL.Func([], [IDL.Vec(WellnessLog)], ['query']),
  'getCallerWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getExerciseById' : IDL.Func([IDL.Nat], [IDL.Opt(Exercise)], ['query']),
  'getExercisesByCategory' : IDL.Func(
      [ExerciseCategory],
      [IDL.Vec(Exercise)],
      ['query'],
    ),
  'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getRecommendedExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getReportedContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getStreakLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isBanned' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinChallenge' : IDL.Func([IDL.Nat], [], []),
  'logWorkout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'moderateContent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'reportUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerNotificationPreferences' : IDL.Func(
      [NotificationPreferences],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateActiveTheme' : IDL.Func([IDL.Text], [], []),
  'updateCallerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateChallengeProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BodyMetric = IDL.Record({
    'bmi' : IDL.Float64,
    'weight' : IDL.Float64,
    'bodyFat' : IDL.Float64,
    'hips' : IDL.Float64,
    'chest' : IDL.Float64,
    'timestamp' : IDL.Int,
    'waist' : IDL.Float64,
    'biceps' : IDL.Float64,
  });
  const ExerciseDifficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const ExerciseCategory = IDL.Variant({
    'shoulders' : IDL.Null,
    'arms' : IDL.Null,
    'back' : IDL.Null,
    'core' : IDL.Null,
    'chest' : IDL.Null,
    'legs' : IDL.Null,
    'fullBody' : IDL.Null,
  });
  const Exercise = IDL.Record({
    'id' : IDL.Nat,
    'equipment' : IDL.Text,
    'musclesWorked' : IDL.Vec(IDL.Text),
    'difficulty' : ExerciseDifficulty,
    'name' : IDL.Text,
    'tier' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'category' : ExerciseCategory,
    'commonMistakes' : IDL.Vec(IDL.Text),
    'setsReps' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'streak' : IDL.Null,
    'levelup' : IDL.Null,
    'challenge' : IDL.Null,
    'friendAchievement' : IDL.Null,
  });
  const SleepData = IDL.Record({
    'hours' : IDL.Float64,
    'bedtime' : IDL.Text,
    'quality' : IDL.Nat,
    'wakeTime' : IDL.Text,
  });
  const WellnessLog = IDL.Record({
    'userId' : IDL.Principal,
    'date' : IDL.Int,
    'sleepData' : SleepData,
    'hydration' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : IDL.Nat,
    'durationDays' : IDL.Nat,
    'badgeIcon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'rewardXp' : IDL.Nat,
    'targetCount' : IDL.Nat,
  });
  const ActivityFeedEntry = IDL.Record({
    'activityType' : IDL.Text,
    'userId' : IDL.Principal,
    'xpGained' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'streak' : IDL.Nat,
    'username' : IDL.Text,
    'fitnessGoal' : IDL.Text,
    'activeTheme' : IDL.Text,
    'level' : IDL.Nat,
    'lastWorkoutDate' : IDL.Int,
    'isBanned' : IDL.Bool,
    'isAdmin' : IDL.Bool,
    'profilePic' : IDL.Opt(ExternalBlob),
  });
  const UserChallenge = IDL.Record({
    'joinedAt' : IDL.Int,
    'completed' : IDL.Bool,
    'challengeId' : IDL.Nat,
    'currentCount' : IDL.Nat,
  });
  const NotificationPreferences = IDL.Record({
    'levelups' : IDL.Bool,
    'friends' : IDL.Bool,
    'challenges' : IDL.Bool,
    'streaks' : IDL.Bool,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'notificationType' : NotificationType,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const WorkoutLog = IDL.Record({
    'completedAt' : IDL.Int,
    'exerciseId' : IDL.Nat,
    'xpAwarded' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'receiverId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'senderId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBodyMetric' : IDL.Func([BodyMetric], [], []),
    'addExercise' : IDL.Func([Exercise], [IDL.Nat], []),
    'addNotification' : IDL.Func(
        [IDL.Principal, NotificationType, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addWellnessLog' : IDL.Func([WellnessLog], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createChallenge' : IDL.Func([Challenge], [IDL.Nat], []),
    'deleteChallenge' : IDL.Func([IDL.Nat], [], []),
    'deleteExercise' : IDL.Func([IDL.Nat], [], []),
    'editChallenge' : IDL.Func([IDL.Nat, Challenge], [], []),
    'editExercise' : IDL.Func([IDL.Nat, Exercise], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getActivityFeed' : IDL.Func([], [IDL.Vec(ActivityFeedEntry)], ['query']),
    'getAdminUserList' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerAchievements' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getCallerBodyMetrics' : IDL.Func([], [IDL.Vec(BodyMetric)], ['query']),
    'getCallerChallenges' : IDL.Func([], [IDL.Vec(UserChallenge)], ['query']),
    'getCallerNotificationPreferences' : IDL.Func(
        [],
        [NotificationPreferences],
        ['query'],
      ),
    'getCallerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWellnessLogs' : IDL.Func([], [IDL.Vec(WellnessLog)], ['query']),
    'getCallerWorkoutLogs' : IDL.Func([], [IDL.Vec(WorkoutLog)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getExerciseById' : IDL.Func([IDL.Nat], [IDL.Opt(Exercise)], ['query']),
    'getExercisesByCategory' : IDL.Func(
        [ExerciseCategory],
        [IDL.Vec(Exercise)],
        ['query'],
      ),
    'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getRecommendedExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getReportedContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getStreakLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isBanned' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinChallenge' : IDL.Func([IDL.Nat], [], []),
    'logWorkout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'moderateContent' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'reportUser' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerNotificationPreferences' : IDL.Func(
        [NotificationPreferences],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateActiveTheme' : IDL.Func([IDL.Text], [], []),
    'updateCallerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateChallengeProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };