/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface NotificationPreferences {
    levelups: boolean;
    friends: boolean;
    challenges: boolean;
    streaks: boolean;
}
export interface WorkoutLog {
    completedAt: bigint;
    exerciseId: bigint;
    xpAwarded: bigint;
    notes: string;
}
export interface Exercise {
    id: bigint;
    equipment: string;
    musclesWorked: Array<string>;
    difficulty: ExerciseDifficulty;
    name: string;
    tier: string;
    instructions: Array<string>;
    category: ExerciseCategory;
    commonMistakes: Array<string>;
    setsReps: string;
}
export interface UserChallenge {
    joinedAt: bigint;
    completed: boolean;
    challengeId: bigint;
    currentCount: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Challenge {
    id: bigint;
    durationDays: bigint;
    badgeIcon: string;
    name: string;
    description: string;
    rewardXp: bigint;
    targetCount: bigint;
}
export interface WellnessLog {
    userId: Principal;
    date: bigint;
    sleepData: SleepData;
    hydration: bigint;
}
export interface Notification {
    id: bigint;
    userId: Principal;
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}
export interface BodyMetric {
    bmi: number;
    weight: number;
    bodyFat: number;
    hips: number;
    chest: number;
    timestamp: bigint;
    waist: number;
    biceps: number;
}
export interface Message {
    content: string;
    receiverId: Principal;
    timestamp: bigint;
    senderId: Principal;
}
export interface ActivityFeedEntry {
    activityType: string;
    userId: Principal;
    xpGained: bigint;
    message: string;
    timestamp: bigint;
}
export interface UserProfile {
    xp: bigint;
    streak: bigint;
    username: string;
    fitnessGoal: string;
    activeTheme: string;
    level: bigint;
    lastWorkoutDate: bigint;
    isBanned: boolean;
    isAdmin: boolean;
    profilePic?: ExternalBlob;
}
export interface SleepData {
    hours: number;
    bedtime: string;
    quality: bigint;
    wakeTime: string;
}
export enum ExerciseCategory {
    shoulders = "shoulders",
    arms = "arms",
    back = "back",
    core = "core",
    chest = "chest",
    legs = "legs",
    fullBody = "fullBody"
}
export enum ExerciseDifficulty {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum NotificationType {
    streak = "streak",
    levelup = "levelup",
    challenge = "challenge",
    friendAchievement = "friendAchievement"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBodyMetric(metric: BodyMetric): Promise<void>;
    addExercise(exercise: Exercise): Promise<bigint>;
    addNotification(userId: Principal, notificationType: NotificationType, message: string): Promise<bigint>;
    addWellnessLog(log: WellnessLog): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(user: Principal): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    createChallenge(challenge: Challenge): Promise<bigint>;
    deleteChallenge(id: bigint): Promise<void>;
    deleteExercise(id: bigint): Promise<void>;
    editChallenge(id: bigint, challenge: Challenge): Promise<void>;
    editExercise(id: bigint, exercise: Exercise): Promise<void>;
    followUser(user: Principal): Promise<void>;
    getActivityFeed(): Promise<Array<ActivityFeedEntry>>;
    getAdminUserList(): Promise<Array<UserProfile>>;
    getAllChallenges(): Promise<Array<Challenge>>;
    getAllExercises(): Promise<Array<Exercise>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getCallerAchievements(): Promise<Array<bigint>>;
    getCallerBodyMetrics(): Promise<Array<BodyMetric>>;
    getCallerChallenges(): Promise<Array<UserChallenge>>;
    getCallerNotificationPreferences(): Promise<NotificationPreferences>;
    getCallerNotifications(): Promise<Array<Notification>>;
    getCallerUserProfile(): Promise<UserProfile>;
    getCallerUserRole(): Promise<UserRole>;
    getCallerWellnessLogs(): Promise<Array<WellnessLog>>;
    getCallerWorkoutLogs(): Promise<Array<WorkoutLog>>;
    getConversation(otherUser: Principal): Promise<Array<Message>>;
    getExerciseById(id: bigint): Promise<Exercise | null>;
    getExercisesByCategory(category: ExerciseCategory): Promise<Array<Exercise>>;
    getGlobalLeaderboard(): Promise<Array<UserProfile>>;
    getRecommendedExercises(): Promise<Array<Exercise>>;
    getReportedContent(): Promise<Array<[bigint, string]>>;
    getStreakLeaderboard(): Promise<Array<UserProfile>>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile>;
    isBanned(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    joinChallenge(challengeId: bigint): Promise<void>;
    logWorkout(exerciseId: bigint, notes: string): Promise<void>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    moderateContent(reportId: bigint, _action: string): Promise<void>;
    reportUser(_user: Principal, reason: string): Promise<void>;
    saveCallerNotificationPreferences(prefs: NotificationPreferences): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(receiverId: Principal, content: string): Promise<void>;
    suspendUser(user: Principal): Promise<void>;
    unfollowUser(user: Principal): Promise<void>;
    updateActiveTheme(newTheme: string): Promise<void>;
    updateCallerProfile(newUsername: string, newGoal: string, newLevel: bigint, newXp: bigint, newStreak: bigint, newPicId: ExternalBlob | null): Promise<void>;
    updateChallengeProgress(_challengeId: bigint, _count: bigint): Promise<void>;
}
import type { Exercise as _Exercise, ExerciseCategory as _ExerciseCategory, ExerciseDifficulty as _ExerciseDifficulty, ExternalBlob as _ExternalBlob, Notification as _Notification, NotificationType as _NotificationType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBodyMetric(arg0: BodyMetric): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBodyMetric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBodyMetric(arg0);
            return result;
        }
    }
    async addExercise(arg0: Exercise): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercise(to_candid_Exercise_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercise(to_candid_Exercise_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNotification(arg0: Principal, arg1: NotificationType, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, to_candid_NotificationType_n14(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, to_candid_NotificationType_n14(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async addWellnessLog(arg0: WellnessLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWellnessLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWellnessLog(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createChallenge(arg0: Challenge): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChallenge(arg0);
            return result;
        }
    }
    async deleteChallenge(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChallenge(arg0);
            return result;
        }
    }
    async deleteExercise(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExercise(arg0);
            return result;
        }
    }
    async editChallenge(arg0: bigint, arg1: Challenge): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editChallenge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editChallenge(arg0, arg1);
            return result;
        }
    }
    async editExercise(arg0: bigint, arg1: Exercise): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editExercise(arg0, to_candid_Exercise_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editExercise(arg0, to_candid_Exercise_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getActivityFeed(): Promise<Array<ActivityFeedEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityFeed();
            return result;
        }
    }
    async getAdminUserList(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUserList();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUserList();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllChallenges(): Promise<Array<Challenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChallenges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChallenges();
            return result;
        }
    }
    async getAllExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExercises();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExercises();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAchievements(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAchievements();
            return result;
        }
    }
    async getCallerBodyMetrics(): Promise<Array<BodyMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerBodyMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerBodyMetrics();
            return result;
        }
    }
    async getCallerChallenges(): Promise<Array<UserChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerChallenges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerChallenges();
            return result;
        }
    }
    async getCallerNotificationPreferences(): Promise<NotificationPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerNotificationPreferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerNotificationPreferences();
            return result;
        }
    }
    async getCallerNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerNotifications();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerNotifications();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_UserProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_UserProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerWellnessLogs(): Promise<Array<WellnessLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWellnessLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWellnessLogs();
            return result;
        }
    }
    async getCallerWorkoutLogs(): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerWorkoutLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerWorkoutLogs();
            return result;
        }
    }
    async getConversation(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getExerciseById(arg0: bigint): Promise<Exercise | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseById(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseById(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExercisesByCategory(arg0: ExerciseCategory): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesByCategory(to_candid_ExerciseCategory_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesByCategory(to_candid_ExerciseCategory_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalLeaderboard(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalLeaderboard();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalLeaderboard();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendedExercises(): Promise<Array<Exercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedExercises();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedExercises();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportedContent(): Promise<Array<[bigint, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportedContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportedContent();
            return result;
        }
    }
    async getStreakLeaderboard(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakLeaderboard();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakLeaderboard();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_UserProfile_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_UserProfile_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isBanned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBanned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBanned();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinChallenge(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinChallenge(arg0);
            return result;
        }
    }
    async logWorkout(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkout(arg0, arg1);
            return result;
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async moderateContent(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moderateContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moderateContent(arg0, arg1);
            return result;
        }
    }
    async reportUser(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportUser(arg0, arg1);
            return result;
        }
    }
    async saveCallerNotificationPreferences(arg0: NotificationPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerNotificationPreferences(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerNotificationPreferences(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async suspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
    async updateActiveTheme(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActiveTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActiveTheme(arg0);
            return result;
        }
    }
    async updateCallerProfile(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerProfile(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerProfile(arg0, arg1, arg2, arg3, arg4, await to_candid_opt_n41(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateChallengeProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChallengeProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChallengeProgress(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ExerciseCategory_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseCategory): ExerciseCategory {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ExerciseDifficulty_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseDifficulty): ExerciseDifficulty {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NotificationType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Exercise]): Exercise | null {
    return value.length === 0 ? null : from_candid_Exercise_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    streak: bigint;
    username: string;
    fitnessGoal: string;
    activeTheme: string;
    level: bigint;
    lastWorkoutDate: bigint;
    isBanned: boolean;
    isAdmin: boolean;
    profilePic: [] | [_ExternalBlob];
}): Promise<{
    xp: bigint;
    streak: bigint;
    username: string;
    fitnessGoal: string;
    activeTheme: string;
    level: bigint;
    lastWorkoutDate: bigint;
    isBanned: boolean;
    isAdmin: boolean;
    profilePic?: ExternalBlob;
}> {
    return {
        xp: value.xp,
        streak: value.streak,
        username: value.username,
        fitnessGoal: value.fitnessGoal,
        activeTheme: value.activeTheme,
        level: value.level,
        lastWorkoutDate: value.lastWorkoutDate,
        isBanned: value.isBanned,
        isAdmin: value.isAdmin,
        profilePic: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePic))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    equipment: string;
    musclesWorked: Array<string>;
    difficulty: _ExerciseDifficulty;
    name: string;
    tier: string;
    instructions: Array<string>;
    category: _ExerciseCategory;
    commonMistakes: Array<string>;
    setsReps: string;
}): {
    id: bigint;
    equipment: string;
    musclesWorked: Array<string>;
    difficulty: ExerciseDifficulty;
    name: string;
    tier: string;
    instructions: Array<string>;
    category: ExerciseCategory;
    commonMistakes: Array<string>;
    setsReps: string;
} {
    return {
        id: value.id,
        equipment: value.equipment,
        musclesWorked: value.musclesWorked,
        difficulty: from_candid_ExerciseDifficulty_n26(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        tier: value.tier,
        instructions: value.instructions,
        category: from_candid_ExerciseCategory_n28(_uploadFile, _downloadFile, value.category),
        commonMistakes: value.commonMistakes,
        setsReps: value.setsReps
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: Principal;
    notificationType: _NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}): {
    id: bigint;
    userId: Principal;
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n33(_uploadFile, _downloadFile, value.notificationType),
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): ExerciseDifficulty {
    return "intermediate" in value ? ExerciseDifficulty.intermediate : "beginner" in value ? ExerciseDifficulty.beginner : "advanced" in value ? ExerciseDifficulty.advanced : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    fullBody: null;
}): ExerciseCategory {
    return "shoulders" in value ? ExerciseCategory.shoulders : "arms" in value ? ExerciseCategory.arms : "back" in value ? ExerciseCategory.back : "core" in value ? ExerciseCategory.core : "chest" in value ? ExerciseCategory.chest : "legs" in value ? ExerciseCategory.legs : "fullBody" in value ? ExerciseCategory.fullBody : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streak: null;
} | {
    levelup: null;
} | {
    challenge: null;
} | {
    friendAchievement: null;
}): NotificationType {
    return "streak" in value ? NotificationType.streak : "levelup" in value ? NotificationType.levelup : "challenge" in value ? NotificationType.challenge : "friendAchievement" in value ? NotificationType.friendAchievement : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n31(_uploadFile, _downloadFile, x));
}
function to_candid_ExerciseCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseCategory): _ExerciseCategory {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ExerciseDifficulty_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseDifficulty): _ExerciseDifficulty {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Exercise_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Exercise): _Exercise {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NotificationType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    xp: bigint;
    streak: bigint;
    username: string;
    fitnessGoal: string;
    activeTheme: string;
    level: bigint;
    lastWorkoutDate: bigint;
    isBanned: boolean;
    isAdmin: boolean;
    profilePic?: ExternalBlob;
}): Promise<{
    xp: bigint;
    streak: bigint;
    username: string;
    fitnessGoal: string;
    activeTheme: string;
    level: bigint;
    lastWorkoutDate: bigint;
    isBanned: boolean;
    isAdmin: boolean;
    profilePic: [] | [_ExternalBlob];
}> {
    return {
        xp: value.xp,
        streak: value.streak,
        username: value.username,
        fitnessGoal: value.fitnessGoal,
        activeTheme: value.activeTheme,
        level: value.level,
        lastWorkoutDate: value.lastWorkoutDate,
        isBanned: value.isBanned,
        isAdmin: value.isAdmin,
        profilePic: value.profilePic ? candid_some(await to_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.profilePic)) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    equipment: string;
    musclesWorked: Array<string>;
    difficulty: ExerciseDifficulty;
    name: string;
    tier: string;
    instructions: Array<string>;
    category: ExerciseCategory;
    commonMistakes: Array<string>;
    setsReps: string;
}): {
    id: bigint;
    equipment: string;
    musclesWorked: Array<string>;
    difficulty: _ExerciseDifficulty;
    name: string;
    tier: string;
    instructions: Array<string>;
    category: _ExerciseCategory;
    commonMistakes: Array<string>;
    setsReps: string;
} {
    return {
        id: value.id,
        equipment: value.equipment,
        musclesWorked: value.musclesWorked,
        difficulty: to_candid_ExerciseDifficulty_n10(_uploadFile, _downloadFile, value.difficulty),
        name: value.name,
        tier: value.tier,
        instructions: value.instructions,
        category: to_candid_ExerciseCategory_n12(_uploadFile, _downloadFile, value.category),
        commonMistakes: value.commonMistakes,
        setsReps: value.setsReps
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseDifficulty): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == ExerciseDifficulty.intermediate ? {
        intermediate: null
    } : value == ExerciseDifficulty.beginner ? {
        beginner: null
    } : value == ExerciseDifficulty.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExerciseCategory): {
    shoulders: null;
} | {
    arms: null;
} | {
    back: null;
} | {
    core: null;
} | {
    chest: null;
} | {
    legs: null;
} | {
    fullBody: null;
} {
    return value == ExerciseCategory.shoulders ? {
        shoulders: null
    } : value == ExerciseCategory.arms ? {
        arms: null
    } : value == ExerciseCategory.back ? {
        back: null
    } : value == ExerciseCategory.core ? {
        core: null
    } : value == ExerciseCategory.chest ? {
        chest: null
    } : value == ExerciseCategory.legs ? {
        legs: null
    } : value == ExerciseCategory.fullBody ? {
        fullBody: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    streak: null;
} | {
    levelup: null;
} | {
    challenge: null;
} | {
    friendAchievement: null;
} {
    return value == NotificationType.streak ? {
        streak: null
    } : value == NotificationType.levelup ? {
        levelup: null
    } : value == NotificationType.challenge ? {
        challenge: null
    } : value == NotificationType.friendAchievement ? {
        friendAchievement: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
